name = "Advent2020"
uuid = "6ab8d1c6-fb3a-4c22-b558-0d4928ea61d6"
authors = ["Jonas Kersulis <kersulis@umich.edu>"]
version = "0.1.0"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
